name: atcc-hifi
group: atcc
platform: pacbio-hifi
reads:
  - /mnt/sda/CommonData/TaxonomyDataset/mock/PacBioHifi-ATCC-MSA-1003.fastq
truth_profile: /mnt/sda/tianqinzhong/code/Chimera/third_party/ChimeraBenchmark/configs/truth/atcc_mock.tsv
