name: atcc-illumina
group: atcc
platform: illumina
paired:
  - /mnt/sda/CommonData/TaxonomyDataset/mock/IIIumina-ATCC-MSA-1003_1.fastq
  - /mnt/sda/CommonData/TaxonomyDataset/mock/IIIumina-ATCC-MSA-1003_2.fastq
truth_profile: /mnt/sda/tianqinzhong/code/Chimera/third_party/ChimeraBenchmark/configs/truth/atcc_mock.tsv
