name: cami2-marine-long-sample0
group: cami2-marine
platform: contigs
reads:
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_0_contigs_anonymous_gsa.fasta
truth_dir: /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/mapping
