name: cami2-marine-long
group: cami2-marine
platform: contigs
reads:
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_0_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_1_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_2_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_3_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_4_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_5_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_6_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_7_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_8_contigs_anonymous_gsa.fasta
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_9_contigs_anonymous_gsa.fasta
truth_dir: /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/mapping
