name: cami-long-sample0
group: cami-long
platform: contigs
reads:
  - /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/fasta/marmgCAMI2_sample_0_contigs_anonymous_gsa.fasta
truth_dir: /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_SHORT/output_dir
truth_map: /mnt/sda/tianqinzhong/project/chimeraBench/dataset/CAMIMARINE_LONG/mapping/marmgCAMI2_sample_0_contigs_gsa_mapping.tsv
