name: zymo-promethion-even
group: zymo
platform: nanopore
type: even
reads:
  - /mnt/sda/CommonData/TaxonomyDataset/mock/Zymo-PromethION-EVEN-BB-SN.fq
truth: /mnt/sda/tianqinzhong/code/Chimera/bench/mock_ground_truth.md
