name: zymo-gridion-log
group: zymo
platform: nanopore
type: log
reads:
  - /mnt/sda/CommonData/TaxonomyDataset/mock/Zymo-GridION-LOG-BB-SN.fq
truth_profile: /mnt/sda/tianqinzhong/code/Chimera/third_party/ChimeraBenchmark/configs/truth/zymo_d6331.tsv
