name: zymo-gridion-log
group: zymo
platform: nanopore
type: log
reads:
  - /mnt/sda/CommonData/TaxonomyDataset/mock/Zymo-GridION-LOG-BB-SN.fq
truth: /mnt/sda/tianqinzhong/code/Chimera/bench/mock_ground_truth.md
